# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7695fb6cd9eb09c61a9c5db31f48c42a3c883a5c1d82b00c2de12470ad0ae44bf702c043e970b177541b17fad8bd82af582ca5d61091bba75673e75b92f85bd4

test:
  secret_key_base: 7470d038f6f9606fbccf07896b298cecf1b8a42db8bb123e6fac7dcf6a0cf16c639a85aac23d01ad0364b67d0a5620d19aa47fba2e22db131f8dce73e77af057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
